### ISSUE TITLE
Player `load` event and callback fire too early

### ISSUE THREAD

**Issue by VanTanev** [videogorillas/vgplayer-api#7]
@chugai judging from our discussion in Slack, I was left with the impression that `load` was supposed to fire after `loadedmetadata` - https://genomeproject.slack.com/archives/videoplayer/p1459192178000222

Again, the reason that I opened #6 was because I need to know when I can access metadata like video duration from the player. `load` event fires BEFORE `loadedmetadata`, and thus cannot be used.

I think that `load` event should fire after `loadedmetadata` _and_ after DOM manipulation is done - ie, it should denote the fact that the full player load cycle has completed, and all player methods are expected to work.

**Comment by chugai** [comment]
Player initialization is not tied up to loadmetadata. What method does not
work?

четвер, 31 березня 2016 р. користувач Ivan Tanev notifications@github.com
написав:

**Comment by VanTanev** [comment]
`getDurationSec`, as mentioned in #6, and the reason I opened that issue to
begin with.

**Comment by VanTanev** [comment]
The issue was tracked down to be related to event order when loading from a separate domain, and fixed on 2016-03-31. Now the `load` event will correctly fire after video metadata is available (ie, `player.getDurationSec()` should now always return the proper value after `load`).

Thanks, @chugai!
