### ISSUE TITLE
Optimization Request for Completed Chunks

### ISSUE THREAD

**Issue by sbutalia** [videogorillas/vgplayer-api#8]
For the API "Get Completed Chunks of a Job"

Please provide an API to get completed chunks for all jobs that are "Started" this will help reduce the amount of calls to the VG APIs when there are a lot of jobs.

**Comment by sysval** [comment]
According to Alex this feature is not a priority at the moment.

**Comment by zhuker** [comment]
@sbutalia use websocket api to listen for job status updates

**Comment by jualshe** [comment]
I assume I can close the ticket
